// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"components/accordion.mdx": () => import("../content/docs/components/accordion.mdx?collection=docs"), "components/alert-dialog.mdx": () => import("../content/docs/components/alert-dialog.mdx?collection=docs"), "components/alert.mdx": () => import("../content/docs/components/alert.mdx?collection=docs"), "components/avatar.mdx": () => import("../content/docs/components/avatar.mdx?collection=docs"), "components/badge.mdx": () => import("../content/docs/components/badge.mdx?collection=docs"), "components/button.mdx": () => import("../content/docs/components/button.mdx?collection=docs"), "components/card.mdx": () => import("../content/docs/components/card.mdx?collection=docs"), "components/checkbox.mdx": () => import("../content/docs/components/checkbox.mdx?collection=docs"), "components/combobox.mdx": () => import("../content/docs/components/combobox.mdx?collection=docs"), "components/dialog.mdx": () => import("../content/docs/components/dialog.mdx?collection=docs"), "components/dropdown-menu.mdx": () => import("../content/docs/components/dropdown-menu.mdx?collection=docs"), "components/input.mdx": () => import("../content/docs/components/input.mdx?collection=docs"), "components/select.mdx": () => import("../content/docs/components/select.mdx?collection=docs"), "components/skeleton.mdx": () => import("../content/docs/components/skeleton.mdx?collection=docs"), "components/switch.mdx": () => import("../content/docs/components/switch.mdx?collection=docs"), "components/tabs.mdx": () => import("../content/docs/components/tabs.mdx?collection=docs"), "components/textarea.mdx": () => import("../content/docs/components/textarea.mdx?collection=docs"), "getting-started/changelog.mdx": () => import("../content/docs/getting-started/changelog.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/introduction.mdx": () => import("../content/docs/getting-started/introduction.mdx?collection=docs"), "getting-started/roadmap.mdx": () => import("../content/docs/getting-started/roadmap.mdx?collection=docs"), "getting-started/theming.mdx": () => import("../content/docs/getting-started/theming.mdx?collection=docs"), "getting-started/troubleshooting.mdx": () => import("../content/docs/getting-started/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;